#define VOXEL_DIST 128
#define TEXTURE_RES 16
#define MAX_LIGHT_COUNT 512
#define SHADOW_CULLING
#define LIGHT_TRACE_LENGTH 30.0
#define LIGHT_RETENTION_RATE 20.0
#define LIGHT_DISCOVERY_RATE 0.01

#ifdef SHADOW_CULLING
#endif